version: '3.8'
services:
  web:
    build: .
    command: bundle exec irb
    volumes:
      - .:/game_on_auth
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:
